import React, {useState} from 'react'

import TableView from 'tableview-library'
import 'tableview-library/dist/index.css'

const App = () => {
  const [data, setData] = useState([{
    "firstName": "Purcell",
    "lastName": "Meale",
    "startDate": "11/09/2006",
    "department": "Services",
    "birthDate": "03/25/2002",
    "street": "Haas",
    "city": "Irvine",
    "state": "California",
    "postalZip": "92710"
  }, {
    "firstName": "Charo",
    "lastName": "Cahalan",
    "startDate": "11/15/2007",
    "department": "Human Resources",
    "birthDate": "03/27/2005",
    "street": "Basil",
    "city": "Bowie",
    "state": "Maryland",
    "postalZip": "20719"
  }, {
    "firstName": "Kendra",
    "lastName": "Coatts",
    "startDate": "12/08/2014",
    "department": "Legal",
    "birthDate": "03/19/1966",
    "street": "East",
    "city": "Chicago",
    "state": "Illinois",
    "postalZip": "60630"
  }, {
    "firstName": "Aila",
    "lastName": "Steptoe",
    "startDate": "07/28/1992",
    "department": "Product Management",
    "birthDate": "03/25/1988",
    "street": "Longview",
    "city": "Tampa",
    "state": "Florida",
    "postalZip": "33680"
  }, {
    "firstName": "Bendicty",
    "lastName": "Medford",
    "startDate": "02/09/1994",
    "department": "Engineering",
    "birthDate": "07/07/1971",
    "street": "Talmadge",
    "city": "Loretto",
    "state": "Minnesota",
    "postalZip": "55598"
  }, {
    "firstName": "Marylou",
    "lastName": "Kestian",
    "startDate": "10/23/1996",
    "department": "Training",
    "birthDate": "04/26/1977",
    "street": "Debra",
    "city": "Detroit",
    "state": "Michigan",
    "postalZip": "48258"
  }, {
    "firstName": "Ozzy",
    "lastName": "Obeney",
    "startDate": "11/29/1999",
    "department": "Legal",
    "birthDate": "12/26/1984",
    "street": "Truax",
    "city": "Savannah",
    "state": "Georgia",
    "postalZip": "31405"
  }, {
    "firstName": "Welsh",
    "lastName": "Burnsell",
    "startDate": "01/10/2016",
    "department": "Services",
    "birthDate": "08/05/1963",
    "street": "Beilfuss",
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "postalZip": "19120"
  }, {
    "firstName": "Gabey",
    "lastName": "Lamcken",
    "startDate": "11/23/2021",
    "department": "Accounting",
    "birthDate": "12/10/1981",
    "street": "Mcguire",
    "city": "Cincinnati",
    "state": "Ohio",
    "postalZip": "45223"
  }, {
    "firstName": "Rayner",
    "lastName": "Dace",
    "startDate": "08/15/2003",
    "department": "Services",
    "birthDate": "03/18/2013",
    "street": "Eagan",
    "city": "Ogden",
    "state": "Utah",
    "postalZip": "84409"
  }, {
    "firstName": "Melinda",
    "lastName": "Levi",
    "startDate": "09/30/2005",
    "department": "Services",
    "birthDate": "02/27/1955",
    "street": "David",
    "city": "Schenectady",
    "state": "New York",
    "postalZip": "12325"
  }, {
    "firstName": "Findley",
    "lastName": "Warburton",
    "startDate": "07/22/2014",
    "department": "Legal",
    "birthDate": "06/25/1961",
    "street": "Arapahoe",
    "city": "Indianapolis",
    "state": "Indiana",
    "postalZip": "46295"
  }, {
    "firstName": "Robinette",
    "lastName": "Devonshire",
    "startDate": "05/12/1997",
    "department": "Business Development",
    "birthDate": "02/01/1971",
    "street": "Tennyson",
    "city": "Minneapolis",
    "state": "Minnesota",
    "postalZip": "55423"
  }, {
    "firstName": "Fay",
    "lastName": "Jansson",
    "startDate": "03/01/1991",
    "department": "Marketing",
    "birthDate": "06/25/2002",
    "street": "Spenser",
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "postalZip": "15266"
  }, {
    "firstName": "Michel",
    "lastName": "Frame",
    "startDate": "10/12/1994",
    "department": "Sales",
    "birthDate": "04/28/1951",
    "street": "Elka",
    "city": "Columbia",
    "state": "South Carolina",
    "postalZip": "29208"
  }, {
    "firstName": "Sharl",
    "lastName": "Cota",
    "startDate": "08/25/2019",
    "department": "Support",
    "birthDate": "06/18/2002",
    "street": "Monument",
    "city": "Farmington",
    "state": "Michigan",
    "postalZip": "48335"
  }, {
    "firstName": "Theadora",
    "lastName": "de Broke",
    "startDate": "10/31/2002",
    "department": "Services",
    "birthDate": "03/02/1976",
    "street": "Crowley",
    "city": "North Las Vegas",
    "state": "Nevada",
    "postalZip": "89036"
  }, {
    "firstName": "Gabie",
    "lastName": "D'Hooge",
    "startDate": "04/08/1990",
    "department": "Human Resources",
    "birthDate": "01/23/1956",
    "street": "Debra",
    "city": "Amarillo",
    "state": "Texas",
    "postalZip": "79159"
  }, {
    "firstName": "Pearle",
    "lastName": "Gullberg",
    "startDate": "12/23/2003",
    "department": "Business Development",
    "birthDate": "02/21/1954",
    "street": "Lighthouse Bay",
    "city": "Yakima",
    "state": "Washington",
    "postalZip": "98907"
  }, {
    "firstName": "Evanne",
    "lastName": "Blything",
    "startDate": "06/06/2017",
    "department": "Sales",
    "birthDate": "01/15/1979",
    "street": "Glendale",
    "city": "Omaha",
    "state": "Nebraska",
    "postalZip": "68124"
  }, {
    "firstName": "Ellswerth",
    "lastName": "Helstrip",
    "startDate": "05/20/1990",
    "department": "Legal",
    "birthDate": "07/05/1982",
    "street": "Vahlen",
    "city": "Santa Ana",
    "state": "California",
    "postalZip": "92705"
  }, {
    "firstName": "Odelia",
    "lastName": "Quiddihy",
    "startDate": "10/18/2021",
    "department": "Research and Development",
    "birthDate": "12/10/2017",
    "street": "Homewood",
    "city": "Arlington",
    "state": "Virginia",
    "postalZip": "22225"
  }, {
    "firstName": "Abbie",
    "lastName": "O'Nowlan",
    "startDate": "04/17/1996",
    "department": "Marketing",
    "birthDate": "01/28/1974",
    "street": "Doe Crossing",
    "city": "Columbia",
    "state": "South Carolina",
    "postalZip": "29220"
  }, {
    "firstName": "Gabbie",
    "lastName": "Sine",
    "startDate": "01/18/2003",
    "department": "Product Management",
    "birthDate": "03/16/1952",
    "street": "Calypso",
    "city": "Salt Lake City",
    "state": "Utah",
    "postalZip": "84105"
  }, {
    "firstName": "Maryl",
    "lastName": "Farndon",
    "startDate": "12/22/2004",
    "department": "Business Development",
    "birthDate": "10/28/1994",
    "street": "Mallory",
    "city": "Fresno",
    "state": "California",
    "postalZip": "93740"
  }, {
    "firstName": "Eamon",
    "lastName": "Drewson",
    "startDate": "03/30/2007",
    "department": "Legal",
    "birthDate": "11/06/1965",
    "street": "Clyde Gallagher",
    "city": "Houston",
    "state": "Texas",
    "postalZip": "77045"
  }, {
    "firstName": "Urbano",
    "lastName": "Spalding",
    "startDate": "03/06/2011",
    "department": "Training",
    "birthDate": "10/26/1996",
    "street": "Orin",
    "city": "Columbus",
    "state": "Ohio",
    "postalZip": "43268"
  }, {
    "firstName": "Justus",
    "lastName": "Capehorn",
    "startDate": "10/24/1996",
    "department": "Research and Development",
    "birthDate": "12/01/1980",
    "street": "Gale",
    "city": "Houston",
    "state": "Texas",
    "postalZip": "77276"
  }, {
    "firstName": "Katine",
    "lastName": "Woodson",
    "startDate": "04/28/2019",
    "department": "Accounting",
    "birthDate": "04/04/2005",
    "street": "Miller",
    "city": "Sioux Falls",
    "state": "South Dakota",
    "postalZip": "57105"
  }, {
    "firstName": "Anthony",
    "lastName": "Kenwood",
    "startDate": "09/21/2004",
    "department": "Legal",
    "birthDate": "12/14/1995",
    "street": "Shasta",
    "city": "Springfield",
    "state": "Illinois",
    "postalZip": "62794"
  }, {
    "firstName": "Spence",
    "lastName": "Cardno",
    "startDate": "06/05/1997",
    "department": "Marketing",
    "birthDate": "08/19/1977",
    "street": "Eagle Crest",
    "city": "Albany",
    "state": "New York",
    "postalZip": "12255"
  }, {
    "firstName": "Averil",
    "lastName": "Inch",
    "startDate": "08/28/1997",
    "department": "Human Resources",
    "birthDate": "12/10/2014",
    "street": "Truax",
    "city": "Phoenix",
    "state": "Arizona",
    "postalZip": "85005"
  }, {
    "firstName": "Winfield",
    "lastName": "Swinfon",
    "startDate": "04/28/2022",
    "department": "Product Management",
    "birthDate": "10/31/2003",
    "street": "Marcy",
    "city": "Philadelphia",
    "state": "Pennsylvania",
    "postalZip": "19109"
  }, {
    "firstName": "Durward",
    "lastName": "Amorine",
    "startDate": "07/14/1993",
    "department": "Legal",
    "birthDate": "05/25/1979",
    "street": "Northfield",
    "city": "Southfield",
    "state": "Michigan",
    "postalZip": "48076"
  }, {
    "firstName": "Jarid",
    "lastName": "McConachie",
    "startDate": "01/02/2017",
    "department": "Support",
    "birthDate": "01/04/1999",
    "street": "Crescent Oaks",
    "city": "Louisville",
    "state": "Kentucky",
    "postalZip": "40287"
  }, {
    "firstName": "Guthrie",
    "lastName": "Effemy",
    "startDate": "08/05/2022",
    "department": "Engineering",
    "birthDate": "11/09/1951",
    "street": "Brentwood",
    "city": "Toledo",
    "state": "Ohio",
    "postalZip": "43656"
  }, {
    "firstName": "Rodd",
    "lastName": "Pochet",
    "startDate": "04/30/2011",
    "department": "Marketing",
    "birthDate": "06/26/1997",
    "street": "Raven",
    "city": "Newark",
    "state": "New Jersey",
    "postalZip": "07104"
  }, {
    "firstName": "Orv",
    "lastName": "Gruczka",
    "startDate": "09/15/2016",
    "department": "Services",
    "birthDate": "03/08/2012",
    "street": "East",
    "city": "Young America",
    "state": "Minnesota",
    "postalZip": "55573"
  }, {
    "firstName": "George",
    "lastName": "Padilla",
    "startDate": "10/29/2020",
    "department": "Human Resources",
    "birthDate": "04/16/1977",
    "street": "Katie",
    "city": "Portland",
    "state": "Oregon",
    "postalZip": "97232"
  }, {
    "firstName": "Bonnie",
    "lastName": "Durdle",
    "startDate": "03/12/2007",
    "department": "Business Development",
    "birthDate": "05/18/1950",
    "street": "Ilene",
    "city": "Sacramento",
    "state": "California",
    "postalZip": "95813"
  }, {
    "firstName": "Lucky",
    "lastName": "Glendenning",
    "startDate": "11/03/1996",
    "department": "Business Development",
    "birthDate": "05/27/1971",
    "street": "Melody",
    "city": "Las Vegas",
    "state": "Nevada",
    "postalZip": "89166"
  }, {
    "firstName": "Barthel",
    "lastName": "Beernt",
    "startDate": "04/23/2017",
    "department": "Business Development",
    "birthDate": "08/05/1988",
    "street": "Graceland",
    "city": "Atlanta",
    "state": "Georgia",
    "postalZip": "30323"
  }, {
    "firstName": "Marthena",
    "lastName": "Emlyn",
    "startDate": "08/22/2014",
    "department": "Accounting",
    "birthDate": "06/29/1973",
    "street": "Esker",
    "city": "Houston",
    "state": "Texas",
    "postalZip": "77060"
  }, {
    "firstName": "Uriah",
    "lastName": "Kilbride",
    "startDate": "06/02/2010",
    "department": "Engineering",
    "birthDate": "11/18/1967",
    "street": "Sunbrook",
    "city": "Beaufort",
    "state": "South Carolina",
    "postalZip": "29905"
  }, {
    "firstName": "Gertie",
    "lastName": "Maytum",
    "startDate": "10/20/1999",
    "department": "Human Resources",
    "birthDate": "06/24/1992",
    "street": "Northview",
    "city": "Dallas",
    "state": "Texas",
    "postalZip": "75246"
  }, {
    "firstName": "Ronny",
    "lastName": "Jepensen",
    "startDate": "11/14/1997",
    "department": "Human Resources",
    "birthDate": "07/20/1956",
    "street": "Warner",
    "city": "Memphis",
    "state": "Tennessee",
    "postalZip": "38150"
  }, {
    "firstName": "Andromache",
    "lastName": "Dineges",
    "startDate": "12/01/2001",
    "department": "Marketing",
    "birthDate": "01/23/1967",
    "street": "Riverside",
    "city": "Cincinnati",
    "state": "Ohio",
    "postalZip": "45233"
  }, {
    "firstName": "Channa",
    "lastName": "Ullrich",
    "startDate": "12/13/2001",
    "department": "Human Resources",
    "birthDate": "07/21/1983",
    "street": "Autumn Leaf",
    "city": "Shawnee Mission",
    "state": "Kansas",
    "postalZip": "66276"
  }, {
    "firstName": "Cristabel",
    "lastName": "Lighterness",
    "startDate": "10/02/2017",
    "department": "Support",
    "birthDate": "01/26/1951",
    "street": "Delladonna",
    "city": "Milwaukee",
    "state": "Wisconsin",
    "postalZip": "53263"
  }, {
    "firstName": "Adams",
    "lastName": "Bigby",
    "startDate": "09/30/2017",
    "department": "Accounting",
    "birthDate": "02/10/1971",
    "street": "Columbus",
    "city": "Oakland",
    "state": "California",
    "postalZip": "94660"
  }, {
    "firstName": "Katya",
    "lastName": "Walkinshaw",
    "startDate": "03/27/1997",
    "department": "Accounting",
    "birthDate": "02/24/1975",
    "street": "Arkansas",
    "city": "Oklahoma City",
    "state": "Oklahoma",
    "postalZip": "73114"
  }, {
    "firstName": "Yale",
    "lastName": "Carillo",
    "startDate": "08/28/2015",
    "department": "Marketing",
    "birthDate": "11/09/1950",
    "street": "Killdeer",
    "city": "Austin",
    "state": "Texas",
    "postalZip": "78764"
  }, {
    "firstName": "Noreen",
    "lastName": "Fenech",
    "startDate": "07/03/2001",
    "department": "Engineering",
    "birthDate": "11/28/1992",
    "street": "Transport",
    "city": "Springfield",
    "state": "Massachusetts",
    "postalZip": "01152"
  }, {
    "firstName": "Rufus",
    "lastName": "Markel",
    "startDate": "07/02/2019",
    "department": "Business Development",
    "birthDate": "05/07/1969",
    "street": "Oxford",
    "city": "Arlington",
    "state": "Virginia",
    "postalZip": "22212"
  }, {
    "firstName": "Toni",
    "lastName": "Moat",
    "startDate": "03/30/2021",
    "department": "Services",
    "birthDate": "12/13/2000",
    "street": "Kings",
    "city": "Trenton",
    "state": "New Jersey",
    "postalZip": "08603"
  }, {
    "firstName": "Monique",
    "lastName": "Klulisek",
    "startDate": "06/27/1998",
    "department": "Sales",
    "birthDate": "05/13/1954",
    "street": "Elgar",
    "city": "Humble",
    "state": "Texas",
    "postalZip": "77346"
  }, {
    "firstName": "Ancell",
    "lastName": "Walak",
    "startDate": "07/11/1992",
    "department": "Engineering",
    "birthDate": "06/28/2003",
    "street": "School",
    "city": "Littleton",
    "state": "Colorado",
    "postalZip": "80126"
  }, {
    "firstName": "Glynda",
    "lastName": "Marshallsay",
    "startDate": "02/26/2013",
    "department": "Accounting",
    "birthDate": "01/19/1956",
    "street": "New Castle",
    "city": "New York City",
    "state": "New York",
    "postalZip": "10009"
  }, {
    "firstName": "Terese",
    "lastName": "Glascott",
    "startDate": "06/30/2019",
    "department": "Product Management",
    "birthDate": "02/21/2018",
    "street": "Lakeland",
    "city": "Houston",
    "state": "Texas",
    "postalZip": "77255"
  }, {
    "firstName": "Baillie",
    "lastName": "Basford",
    "startDate": "02/20/2015",
    "department": "Engineering",
    "birthDate": "07/08/1985",
    "street": "Eliot",
    "city": "Torrance",
    "state": "California",
    "postalZip": "90505"
  }, {
    "firstName": "Smitty",
    "lastName": "Batstone",
    "startDate": "07/25/1997",
    "department": "Business Development",
    "birthDate": "06/17/1969",
    "street": "Birchwood",
    "city": "Norwalk",
    "state": "Connecticut",
    "postalZip": "06859"
  }, {
    "firstName": "Paton",
    "lastName": "Brunelli",
    "startDate": "02/17/2011",
    "department": "Accounting",
    "birthDate": "03/11/1951",
    "street": "Golf Course",
    "city": "Rockford",
    "state": "Illinois",
    "postalZip": "61110"
  }, {
    "firstName": "Alma",
    "lastName": "Piggott",
    "startDate": "11/27/2008",
    "department": "Human Resources",
    "birthDate": "04/07/1956",
    "street": "Vernon",
    "city": "Peoria",
    "state": "Arizona",
    "postalZip": "85383"
  }, {
    "firstName": "Marylou",
    "lastName": "Dowdle",
    "startDate": "07/10/1990",
    "department": "Human Resources",
    "birthDate": "09/07/1985",
    "street": "Farragut",
    "city": "Savannah",
    "state": "Georgia",
    "postalZip": "31410"
  }, {
    "firstName": "Frankie",
    "lastName": "Thorns",
    "startDate": "12/29/1994",
    "department": "Sales",
    "birthDate": "11/27/1956",
    "street": "Starling",
    "city": "Denver",
    "state": "Colorado",
    "postalZip": "80279"
  }, {
    "firstName": "Dall",
    "lastName": "Bowles",
    "startDate": "01/18/2010",
    "department": "Services",
    "birthDate": "12/15/1969",
    "street": "Lakewood Gardens",
    "city": "Houston",
    "state": "Texas",
    "postalZip": "77015"
  }, {
    "firstName": "Scotty",
    "lastName": "Ayliffe",
    "startDate": "11/15/2007",
    "department": "Sales",
    "birthDate": "12/09/1972",
    "street": "Jana",
    "city": "Boston",
    "state": "Massachusetts",
    "postalZip": "02203"
  }, {
    "firstName": "Hobart",
    "lastName": "Dekeyser",
    "startDate": "11/28/1990",
    "department": "Product Management",
    "birthDate": "07/11/1974",
    "street": "Service",
    "city": "Crawfordsville",
    "state": "Indiana",
    "postalZip": "47937"
  }, {
    "firstName": "Maddy",
    "lastName": "Adamczewski",
    "startDate": "10/02/2007",
    "department": "Research and Development",
    "birthDate": "10/03/1965",
    "street": "Tony",
    "city": "Boise",
    "state": "Idaho",
    "postalZip": "83727"
  }, {
    "firstName": "Currey",
    "lastName": "Klimowski",
    "startDate": "04/06/1993",
    "department": "Sales",
    "birthDate": "07/06/2001",
    "street": "Gina",
    "city": "Lubbock",
    "state": "Texas",
    "postalZip": "79415"
  }, {
    "firstName": "Evyn",
    "lastName": "Thews",
    "startDate": "04/16/1993",
    "department": "Research and Development",
    "birthDate": "01/04/2004",
    "street": "Rockefeller",
    "city": "Washington",
    "state": "District of Columbia",
    "postalZip": "20067"
  }, {
    "firstName": "Silas",
    "lastName": "Nimmo",
    "startDate": "04/13/2015",
    "department": "Services",
    "birthDate": "05/02/1965",
    "street": "Burrows",
    "city": "New Haven",
    "state": "Connecticut",
    "postalZip": "06533"
  }, {
    "firstName": "Karlen",
    "lastName": "Fealy",
    "startDate": "01/19/2017",
    "department": "Human Resources",
    "birthDate": "11/02/2021",
    "street": "Spaight",
    "city": "Worcester",
    "state": "Massachusetts",
    "postalZip": "01610"
  }, {
    "firstName": "Leila",
    "lastName": "Jeffcoate",
    "startDate": "08/11/2019",
    "department": "Engineering",
    "birthDate": "07/10/1997",
    "street": "Sage",
    "city": "Syracuse",
    "state": "New York",
    "postalZip": "13210"
  }, {
    "firstName": "Deeanne",
    "lastName": "Allgood",
    "startDate": "01/06/1997",
    "department": "Support",
    "birthDate": "03/04/1974",
    "street": "Northfield",
    "city": "Macon",
    "state": "Georgia",
    "postalZip": "31296"
  }, {
    "firstName": "Des",
    "lastName": "Ottiwill",
    "startDate": "02/22/2022",
    "department": "Legal",
    "birthDate": "07/07/1987",
    "street": "Acker",
    "city": "Huntington",
    "state": "West Virginia",
    "postalZip": "25716"
  }, {
    "firstName": "Jocko",
    "lastName": "Grisedale",
    "startDate": "11/22/2005",
    "department": "Services",
    "birthDate": "04/12/1951",
    "street": "Merchant",
    "city": "Cincinnati",
    "state": "Ohio",
    "postalZip": "45203"
  }, {
    "firstName": "Chery",
    "lastName": "Backes",
    "startDate": "01/22/1996",
    "department": "Accounting",
    "birthDate": "01/10/2016",
    "street": "Grim",
    "city": "New York City",
    "state": "New York",
    "postalZip": "10131"
  }, {
    "firstName": "Jelene",
    "lastName": "Mumby",
    "startDate": "02/16/2016",
    "department": "Engineering",
    "birthDate": "09/10/2011",
    "street": "Mesta",
    "city": "Austin",
    "state": "Texas",
    "postalZip": "78769"
  }, {
    "firstName": "Loralie",
    "lastName": "Jeenes",
    "startDate": "06/28/2015",
    "department": "Research and Development",
    "birthDate": "10/21/2020",
    "street": "Eliot",
    "city": "Sacramento",
    "state": "California",
    "postalZip": "95823"
  }, {
    "firstName": "Linzy",
    "lastName": "Crosdill",
    "startDate": "11/02/2010",
    "department": "Research and Development",
    "birthDate": "03/17/1975",
    "street": "Mosinee",
    "city": "Arlington",
    "state": "Virginia",
    "postalZip": "22205"
  }, {
    "firstName": "Oralee",
    "lastName": "Elby",
    "startDate": "01/01/2002",
    "department": "Product Management",
    "birthDate": "05/17/1991",
    "street": "Westport",
    "city": "Huntington",
    "state": "West Virginia",
    "postalZip": "25775"
  }, {
    "firstName": "Deni",
    "lastName": "Bertie",
    "startDate": "05/29/2001",
    "department": "Sales",
    "birthDate": "04/14/1981",
    "street": "Waubesa",
    "city": "Long Beach",
    "state": "California",
    "postalZip": "90810"
  }, {
    "firstName": "Tarrah",
    "lastName": "McClinton",
    "startDate": "08/05/2006",
    "department": "Training",
    "birthDate": "05/21/1957",
    "street": "Vermont",
    "city": "Charlotte",
    "state": "North Carolina",
    "postalZip": "28278"
  }, {
    "firstName": "Barbabra",
    "lastName": "Crayk",
    "startDate": "04/05/1998",
    "department": "Product Management",
    "birthDate": "08/12/1968",
    "street": "Magdeline",
    "city": "Cincinnati",
    "state": "Ohio",
    "postalZip": "45208"
  }, {
    "firstName": "Lorrie",
    "lastName": "Blower",
    "startDate": "04/16/1999",
    "department": "Legal",
    "birthDate": "08/22/1970",
    "street": "Prentice",
    "city": "Norwalk",
    "state": "Connecticut",
    "postalZip": "06859"
  }, {
    "firstName": "Maribeth",
    "lastName": "Jarman",
    "startDate": "11/20/1995",
    "department": "Services",
    "birthDate": "04/26/1957",
    "street": "Dunning",
    "city": "Kingsport",
    "state": "Tennessee",
    "postalZip": "37665"
  }, {
    "firstName": "Tommy",
    "lastName": "Raspin",
    "startDate": "10/15/2006",
    "department": "Research and Development",
    "birthDate": "09/15/1985",
    "street": "Nova",
    "city": "Hartford",
    "state": "Connecticut",
    "postalZip": "06152"
  }, {
    "firstName": "Rouvin",
    "lastName": "Biddulph",
    "startDate": "08/20/1995",
    "department": "Legal",
    "birthDate": "10/04/2008",
    "street": "Hallows",
    "city": "Hartford",
    "state": "Connecticut",
    "postalZip": "06105"
  }, {
    "firstName": "Putnam",
    "lastName": "Cooksley",
    "startDate": "07/22/2022",
    "department": "Human Resources",
    "birthDate": "01/01/2018",
    "street": "Tennessee",
    "city": "Muncie",
    "state": "Indiana",
    "postalZip": "47306"
  }, {
    "firstName": "Phillipe",
    "lastName": "Shedden",
    "startDate": "03/19/1994",
    "department": "Accounting",
    "birthDate": "03/16/2008",
    "street": "Browning",
    "city": "Muncie",
    "state": "Indiana",
    "postalZip": "47306"
  }, {
    "firstName": "Ronna",
    "lastName": "Hankin",
    "startDate": "08/14/1992",
    "department": "Business Development",
    "birthDate": "10/04/1971",
    "street": "Charing Cross",
    "city": "Muskegon",
    "state": "Michigan",
    "postalZip": "49444"
  }, {
    "firstName": "Darrick",
    "lastName": "Hawkey",
    "startDate": "06/14/2000",
    "department": "Marketing",
    "birthDate": "12/28/1979",
    "street": "Merrick",
    "city": "Atlanta",
    "state": "Georgia",
    "postalZip": "30356"
  }, {
    "firstName": "Guendolen",
    "lastName": "Himsworth",
    "startDate": "04/12/1993",
    "department": "Support",
    "birthDate": "07/12/2013",
    "street": "Harper",
    "city": "South Lake Tahoe",
    "state": "California",
    "postalZip": "96154"
  }, {
    "firstName": "Fielding",
    "lastName": "Goodhall",
    "startDate": "12/14/2002",
    "department": "Training",
    "birthDate": "07/30/1981",
    "street": "Kensington",
    "city": "Dayton",
    "state": "Ohio",
    "postalZip": "45414"
  }, {
    "firstName": "Ly",
    "lastName": "Traske",
    "startDate": "08/27/1990",
    "department": "Support",
    "birthDate": "08/11/2010",
    "street": "Dunning",
    "city": "Kansas City",
    "state": "Missouri",
    "postalZip": "64114"
  }, {
    "firstName": "Nowell",
    "lastName": "Thursby",
    "startDate": "04/16/1993",
    "department": "Sales",
    "birthDate": "09/14/2014",
    "street": "Elka",
    "city": "Oklahoma City",
    "state": "Oklahoma",
    "postalZip": "73173"
  }, {
    "firstName": "Almire",
    "lastName": "Carss",
    "startDate": "05/10/2012",
    "department": "Business Development",
    "birthDate": "07/25/2001",
    "street": "Monica",
    "city": "Detroit",
    "state": "Michigan",
    "postalZip": "48295"
  }, {
    "firstName": "Corissa",
    "lastName": "Thurman",
    "startDate": "10/07/1996",
    "department": "Engineering",
    "birthDate": "03/12/2019",
    "street": "Marquette",
    "city": "Birmingham",
    "state": "Alabama",
    "postalZip": "35205"
  }, {
    "firstName": "Mano",
    "lastName": "Adanet",
    "startDate": "06/17/2003",
    "department": "Sales",
    "birthDate": "05/07/1986",
    "street": "Sloan",
    "city": "Glendale",
    "state": "California",
    "postalZip": "91210"
  }
]);
  const dataName =
    [
      "First Name",
      "Last Name",
      "Start Date",
      "Departement",
      "Date of Birth",
      "Street",
      "City",
      "State",
      "Zip Code",
    ]

  const keys = ["firstName", "lastName", "startDate", "department", "birthDate", "street", "city", "state", "postalZip"]
  return <TableView
    columns={dataName}
    datas={data}
    setDatas={setData}
    keys={keys} />
}

export default App
